// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljfubranindkcrniiobq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZnVicmFuaW5ka2Nybmlpb2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3NTA4ODUsImV4cCI6MjA4MzMyNjg4NX0.SS5eyPNmwd4um9j4P7PwRlUrK7LWkwqRHscZiBR5W-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});